### ISSUE TITLE
Set color for pdf-resizer

### ISSUE THREAD

**Issue by Crowds21** [mendax1234/logseq-cusgit-theme#2]
Nice theme !

When I browse PDF in logseq, I need to change its screen proportion. But it is difficult to find `resizer` under the current theme.
<img width="978" alt="截屏2022-06-02 10 34 32" src="https://user-images.githubusercontent.com/48215334/171539657-33991d88-736c-4f26-8765-410130a0622d.png">

**Comment by mendax1234** [comment]
Thanks for your suggestion!
l have published a new version, and you can see if it works well now! 
If you have any other good suggestions about this theme, feel free to propose them! Thanks

Daniel

**Comment by mendax1234** [comment]
If you don't have any other questions , l will close this issue.
