### ISSUE TITLE
[Bug] Overlapping elements for advanced queries

### ISSUE THREAD

**Issue by piyush-das** [mendax1234/logseq-cusgit-theme#5]
Hi, 
![image](https://user-images.githubusercontent.com/68941107/173235447-ffefe03a-a9b3-4016-96b8-99c9df701662.png)
The Table view toggle button overlaps with the number of results of the query if title is h2
Thanks

**Comment by mendax1234** [comment]
Can you provide some detailed information about this bug , like showing your "code" of this specific part and l can have a check on it. Besides , l am very busy recently and l may not reply to you timely. Sorry for the inconvenience.

**Comment by piyush-das** [comment]
Sure. Here's the code for generating it.
```clojure
#+BEGIN_QUERY
{
:title  [ :h1 " Attempted Questions"]
:query [
       :find (pull ?p [*]) 
       :where (page-property ?p :source "Leetcode")]
}
#+END_QUERY
```
This would generate something like this. 
![image](https://user-images.githubusercontent.com/68941107/174061918-848fd419-965f-4d3f-a43b-0c847ff99eb3.png)

It's perfectly all right, take your time. Loving your theme. I have reduced the header to an "h3" and that doesn't give me an overlap at all.
Great work !

**Comment by mendax1234** [comment]
> Sure. Here's the code for generating it.
> 
> ```clojure
> #+BEGIN_QUERY
> {
> :title  [ :h1 " Attempted Questions"]
> :query [
>        :find (pull ?p [*]) 
>        :where (page-property ?p :source "Leetcode")]
> }
> #+END_QUERY
> ```
> 
> This would generate something like this. ![image](https://user-images.githubusercontent.com/68941107/174061918-848fd419-965f-4d3f-a43b-0c847ff99eb3.png)
> 
> It's perfectly all right, take your time. Loving your theme. I have reduced the header to an "h3" and that doesn't give me an overlap at all. Great work !

Got it, l am working to fix it!

**Comment by mendax1234** [comment]
@piyush-das  Let me know if this works well
The light mode:
![image](https://user-images.githubusercontent.com/62934294/174475740-f033ca10-9eca-4a5e-93e1-6cc54d83570b.png)

The dark mode:
![image](https://user-images.githubusercontent.com/62934294/174475745-ab9f7532-7691-4c16-8a79-1269602fda03.png)

l will publish the latest version soon! If you have any further suggestions , feel free to put forward them here!

**Comment by piyush-das** [comment]
Love it !

**Comment by mendax1234** [comment]
Oops. Can you share your code again?

**Comment by piyush-das** [comment]
> > Sure. Here's the code for generating it.
> > ```clojure
> > #+BEGIN_QUERY
> > {
> > :title  [ :h1 " Attempted Questions"]
> > :query [
> >        :find (pull ?p [*]) 
> >        :where (page-property ?p :source "Leetcode")]
> > }
> > #+END_QUERY
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This would generate something like this. ![image](https://github.com/assets/68941107/848fd419-965f-4d3f-a43b-0c847ff99eb3)
> > It's perfectly all right, take your time. Loving your theme. I have reduced the header to an "h3" and that doesn't give me an overlap at all. Great work !
> 
> Got it, l am working to fix it!

It's the same one, that I used previously. Maybe it would show up only when you actually do have results returning for the query.

**Comment by mendax1234** [comment]
> It's the same one, that I used previously. Maybe it would show up only when you actually do have results returning for the query.

Since l am not familiar with query's syntax, so would you please provide your code so l can focus on the problem. Thanks.

**Comment by piyush-das** [comment]
This is the whole code. Just create a new Page named Testing Page and put the following in it:
```
source:: TestProperty
```

**Comment by mendax1234** [comment]
> source:: TestProperty

Got it! Thanks for replying. Maybe l will fix it soon!

**Comment by piyush-das** [comment]
Yup, the overlap is fixed. Can we have the enclosing side border prior to the fix.It might be a personal preference but I loved the aesthetics of it.

**Comment by mendax1234** [comment]
> Yup, the overlap is fixed. Can we have the enclosing side border prior to the fix. It might be a personal preference but I loved the aesthetics of it.

@piyush-das 
Does this fit you demand?
![image](https://user-images.githubusercontent.com/62934294/175191646-7e3a6871-8e93-45d4-b959-2a2e1e171682.png)

**Comment by piyush-das** [comment]
I meant this.
![image](https://user-images.githubusercontent.com/68941107/175290900-a62382b5-2120-40a0-b33b-fa84cfc1d737.png)
I loved the curled border around the whole query. Although it's not a demand, only if you like the aesthetics as well. :)

**Comment by mendax1234** [comment]
> I loved the curled border around the whole query. Although it's not a demand, only if you like the aesthetics as well. :)

Yes, l have added the curled border around the whole query, you can upgrade to the latest version to check if it works for you. The latest version is 1.2.2

**Comment by piyush-das** [comment]
Although I preferred the previous borders more with the top border not completed. But this looks great as well. Thanks again for the great theme :)

**Comment by mendax1234** [comment]
If you have no problems, l will close this issue. Thanks for finding this bug about query table!
