### ISSUE TITLE
Bullet threading plugin looks wrong

### ISSUE THREAD

**Issue by alan-nicolas** [mendax1234/logseq-cusgit-theme#6]
I'm loving this theme! But I use the plugin "Bullet Threading" and the visuals break. :'(

![image](https://user-images.githubusercontent.com/37817904/178186276-d13757f1-34b9-4241-a003-c89228853b62.png)

Maybe you have the time to make it work.

Thank you!

**Comment by mendax1234** [comment]
Thanks for finding this bug! Would you mind providing the steps to reproduce this bug?

**Comment by alan-nicolas** [comment]
Oh, now I see. It wasn't as simple. It has to do with the using the `#card` on my end

1. Install "Bullet Threading" extension
2. Install your "logseq-cusgit-theme"
3. Add a `#card` to an item, add a nested item, and there, it breaks.

Thank you for reading

**Comment by mendax1234** [comment]
> Oh, now I see. It wasn't as simple. It has to do with the using the `#card` on my end
> 
> 1. Install "Bullet Threading" extension
> 2. Install your "logseq-cusgit-theme"
> 3. Add a `#card` to an item, add a nested item, and there, it breaks.
> 
> Thank you for reading
> 
> (Even with just one card. But there in the screenshot I have nested `#card`s.)

Thanks! l may fix it when l have time!

**Comment by mendax1234** [comment]
> Oh, now I see. It wasn't as simple. It has to do with the using the `#card` on my end
> 
> 1. Install "Bullet Threading" extension
> 2. Install your "logseq-cusgit-theme"
> 3. Add a `#card` to an item, add a nested item, and there, it breaks.
> 
> Thank you for reading
> 
> (Even with just one card. But there in the screenshot I have nested `#card`s.)

![image](https://user-images.githubusercontent.com/62934294/178189081-2e713557-c140-4262-9e85-d3cc8c52a41e.png)
l don't know whether this works well now. l will publish a new version and you can check whether it works now!

**Comment by alan-nicolas** [comment]
So, now bullet threading works. BUT the nice boxes showing nested `#cards` disappeared on my end of things

**Comment by mendax1234** [comment]
> So, now bullet threading works. BUT the nice boxes showing nested `#cards` disappeared on my end of things

What do you mean by the nice boxes? Can you take a screenshot?

**Comment by alan-nicolas** [comment]
Yes, sorry:

![image](https://user-images.githubusercontent.com/37817904/178190761-08ced63d-dcdd-4cdc-bb69-ad5d0d4e4ecb.png)

So, before all cards where marked by a surrounding box, and so where nested cards within cards.

Based on what little I know I'd say you removed the box, because the threading was conflicting with the margin.

What if instead of "border" CSS property you use "outline" which, I think I remember, doesn't need margin and so avoids the conflict, maybe. Sorry if I'm talking silliness or if it's not a semantic solution.

**Comment by alan-nicolas** [comment]
Also, thank you for the immense speed of feedback and code! :)

**Comment by mendax1234** [comment]
> Yes, sorry:
> 
> ![image](https://user-images.githubusercontent.com/37817904/178190761-08ced63d-dcdd-4cdc-bb69-ad5d0d4e4ecb.png)
> 
> So, before all cards where marked by a surrounding box, and so where nested cards within cards.
> 
> Based on what little I know I'd say you removed the box, because the threading was conflicting with the margin.
> 
> What if instead of "border" CSS property you use "outline" which, I think I remember, doesn't need margin and so avoids the conflict, maybe. Sorry if I'm talking silliness or if it's not a semantic solution.

Thanks for your advice and l have found where the bug lies, it is not in the outline or border, it is the `margin-left` which makes this bug.
After l delete these three lines, everything works well with the nice boxes!
```
div[data-refs-self*='"card"'] > div:first-child {
  margin-left: -0.5em;
}
```

The effect:
![image](https://user-images.githubusercontent.com/62934294/178193611-9d837d7a-70f3-444c-b9f9-efdddd20ba0b.png)


Thanks for your suggestions! l will publish a new version!

**Comment by alan-nicolas** [comment]
@mendax1234 That was amazing. You are very kind. It works flawlessly now!

Thank you! :)
