### ISSUE TITLE
Sidebar inconsistent spacing.

### ISSUE THREAD

**Issue by e0lithic** [mendax1234/logseq-cusgit-theme#8]
Hi,

I am currently using version 0.8.8 logseq with the theme's 1.3.2 version.

Here is an overview of the issue.
The sidebar with the emojis seems to work just fine on the journal page.
![image](https://user-images.githubusercontent.com/11680315/193437316-5b731f98-afe7-4fc4-b176-7409ea21b15d.png)
However, if I navigate to some other page, the sidebar spacing breaks.
![image](https://user-images.githubusercontent.com/11680315/193437325-3c9f49d8-72e2-45c9-b124-624091a09c66.png)

Please let me know if I am missing something in the configurations.

Thanks.

**Comment by mendax1234** [comment]
> 

Hi, thanks for reporting this problem first! However, when l test it on my Logseq, which is also 0.8.8, it seems that these is no problem with it. 

Can you send some of your pages with emojis to me so that l can test whether it is a problem with my theme? Thanks!

**Comment by e0lithic** [comment]
Here is one of the pages. Maybe marking them as favorite will cause the problem.
```md
icon:: ❓

- DONE https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/
  :LOGBOOK:
  CLOCK: [2022-08-02 Tue 07:27:59]--[2022-08-02 Tue 07:28:00] =>  00:00:01
  CLOCK: [2022-08-02 Tue 07:28:01]--[2022-08-02 Tue 07:28:02] =>  00:00:01
  CLOCK: [2022-08-02 Tue 07:28:02]--[2022-08-02 Tue 07:28:04] =>  00:00:02
  CLOCK: [2022-08-02 Tue 07:28:07]--[2022-08-02 Tue 07:28:08] =>  00:00:01
  CLOCK: [2022-08-02 Tue 07:28:09]--[2022-08-02 Tue 07:28:09] =>  00:00:00
  CLOCK: [2022-08-02 Tue 07:28:13]--[2022-08-02 Tue 07:28:14] =>  00:00:01
  CLOCK: [2022-08-17 Wed 11:09:19]--[2022-08-17 Wed 11:09:20] =>  00:00:01
  CLOCK: [2022-08-17 Wed 11:09:21]--[2022-08-17 Wed 11:09:21] =>  00:00:00
  CLOCK: [2022-08-17 Wed 11:09:22]--[2022-08-17 Wed 11:09:24] =>  00:00:02
  CLOCK: [2022-08-17 Wed 11:09:27]--[2022-08-17 Wed 11:09:29] =>  00:00:02
  :END:
- TODO https://leetcode.com/problems/swapping-nodes-in-a-linked-list/
- TODO https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k
```

**Comment by mendax1234** [comment]
> Here is one of the pages. Maybe marking them as favorite will cause the problem.
> 
> ```lisp
> icon:: ❓
> 
> - DONE https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/
>   :LOGBOOK:
>   CLOCK: [2022-08-02 Tue 07:27:59]--[2022-08-02 Tue 07:28:00] =>  00:00:01
>   CLOCK: [2022-08-02 Tue 07:28:01]--[2022-08-02 Tue 07:28:02] =>  00:00:01
>   CLOCK: [2022-08-02 Tue 07:28:02]--[2022-08-02 Tue 07:28:04] =>  00:00:02
>   CLOCK: [2022-08-02 Tue 07:28:07]--[2022-08-02 Tue 07:28:08] =>  00:00:01
>   CLOCK: [2022-08-02 Tue 07:28:09]--[2022-08-02 Tue 07:28:09] =>  00:00:00
>   CLOCK: [2022-08-02 Tue 07:28:13]--[2022-08-02 Tue 07:28:14] =>  00:00:01
>   CLOCK: [2022-08-17 Wed 11:09:19]--[2022-08-17 Wed 11:09:20] =>  00:00:01
>   CLOCK: [2022-08-17 Wed 11:09:21]--[2022-08-17 Wed 11:09:21] =>  00:00:00
>   CLOCK: [2022-08-17 Wed 11:09:22]--[2022-08-17 Wed 11:09:24] =>  00:00:02
>   CLOCK: [2022-08-17 Wed 11:09:27]--[2022-08-17 Wed 11:09:29] =>  00:00:02
>   :END:
> - TODO https://leetcode.com/problems/swapping-nodes-in-a-linked-list/
> - TODO https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k
> ```

I don't whether my settings is the same as yours since everything goes well on my Logseq.

<img width="176" alt="image" src="https://user-images.githubusercontent.com/62934294/193748918-0aca786f-caaf-4882-9fe4-5c85cc8870e1.png">
Would you mind sharing the detailed steps to make this `bug`?

**Comment by e0lithic** [comment]
One of the things, which I am noticing is the fact that the emoji in my case appear on the left side whereas in your case they appear on the right side of the text, perhaps there is a configuration for this. I will try to figure if I have something other than the default

**Comment by mendax1234** [comment]
> One of the things, which I am noticing is the fact that the emoji in my case appear on the left side whereas in your case they appear on the right side of the text, perhaps there is a configuration for this. I will try to figure if I have something other than the default. ![image](https://user-images.githubusercontent.com/11680315/193885747-8763ef89-50b2-485b-af61-40c512d294e5.png)

I try making your bug appear on my Logseq, but it seems that everything goes well. l have changed the emoji to the left side and navigate to other pages.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/62934294/194015547-f76d84a5-695e-41db-bbe4-95e3b578209f.png">

**Comment by mendax1234** [comment]
> I will try to initialize a new logseq database from scratch(defaults) and try to recreate the issue.

If the problems also exist with a new logseq database, please post the detailed steps in this issue. Thanks!
